### ISSUE TITLE
Missing instructions for creation od the EDAnalyzer in: https://cms-opendata-workshop.github.io/workshop-lesson-cmssw/04_source/index.html

### ISSUE THREAD

**Issue by JonaJJSJ-crypto** [JonaJJSJ-crypto/Proyecto-de-Tesis#1]

**Comment by JonaJJSJ-crypto** [comment]
Generate an ssh key in the container works well even with the outdated git.

**Comment by caredg** [comment]
> Generate an ssh key in the container works well even with the outdated git.

Entonces esto sí funcionó?

**Comment by JonaJJSJ-crypto** [comment]
Ya corrijo eso

Get Outlook para Android<https://aka.ms/AAb9ysg>

________________________________
