### ISSUE TITLE
Create a table that relates pre-selected datasets + Run number viability.

### ISSUE THREAD

**Issue by JonaJJSJ-crypto** [JonaJJSJ-crypto/Proyecto-de-Tesis#13]

**Comment by JonaJJSJ-crypto** [comment]
![Triggers](https://user-images.githubusercontent.com/78813250/115887389-7fc8c800-a417-11eb-957a-200dce95bcc1.png)

**Comment by caredg** [comment]
Closed/superseded by #32

**Comment by caredg** [comment]
Superseded by #32.  Closing....
