### ISSUE TITLE
Problems with the trigger prescales analyzer

### ISSUE THREAD

**Issue by JonaJJSJ-crypto** [JonaJJSJ-crypto/Proyecto-de-Tesis#15]
![Prescale error](https://user-images.githubusercontent.com/78813250/117468760-a1977400-af1a-11eb-9e8f-4b0e55d53895.png)
It seems there is a problem related with the trigger prescales Analyzer

**Comment by caredg** [comment]
Esto fue por el acceso a la base de datos de condiciones, cierto?  Lo cerramos @JonaJJSJ-crypto ?
