### ISSUE TITLE
LHE files wih only two Events, this problem could be originated in UFOmodel.

### ISSUE THREAD

**Issue by JonaJJSJ-crypto** [JonaJJSJ-crypto/Proyecto-de-Tesis#19]
Generating the process (p p > lwe+ lwe- > z z e+ e-) with 10.000 events, only stores 2 events in the .lhe file

**Comment by caredg** [comment]
@JonaJJSJ-crypto quizá esto vendría mejor como comentario a #7 o #18, no? a menos que se torne en un actividad específica por sí misma...

**Comment by JonaJJSJ-crypto** [comment]
I noticed that only considering the process for Pair of LW-leptons (generate  p p > lwe+ lwe- )There is no problem in the number of events stored in the .lhe file. I also noticed that modifying the process as a decay process (generate p p > lwe+ lwe- (lwe+ > Z e+, lwe- > Z e-)) corrects the cross section calculation for this process. Yet there is still few stored events in .lhe file. I can conclude that this is problem is given because of the coupling factor for the decay (lwe > Z e) because this has a magnitude gweak*2.5x10^-6. 
This Coupling factor is well calculated and has been double checked, and must be okay since the probability for an electron decaying into a LW-lepton should be minimum. But I'm not so sure about the opposite case, by this meaning that with the actual model the LW-lepton has a minimum probability to decay into an electron. I need more time to think about this process

**Comment by JonaJJSJ-crypto** [comment]
Increasing the Beam-Energy seems to have no effect

**Comment by caredg** [comment]
Maybe there are some hints here: https://answers.launchpad.net/mg5amcnlo/+question/200766

**Comment by JonaJJSJ-crypto** [comment]
[unweighted_events.lhe.gz](https://github.com/JonaJJSJ-crypto/Proyecto-de-Tesis/files/6679918/unweighted_events.lhe.gz)
I finally manage to fix this issue yet there appear some problem relate to Cross-Section. But should not be a problem to advance forward. As mentioned in the Q&A of Madgraph the problem were due to the small widths. Things that didn't work were artificially rescaling the decays widths, nor calculating the widths and inserting them into the param card. 
What i found worked was Constructing the UFO files with the Width set in Auto the Whole process. This maybe could be inserted directly derectly in the parameters of the model But im working on other things right now. 
The UFO Models are in the OneDrive, and After finishing the whole simulation they will be in this repository.
