### ISSUE TITLE
Plot basic and tracking/vertexing variables for our LW simulation

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/Proyecto-de-Tesis#22]
After completing #7 and making sure it works ok, we should plot a few variables to understand the kinematics, and the whole geometry of these kind of events.  So, we should plot pT, eta, phi, E, variables, but also number of primary vertices, vx, vy, vz, distribution of track pT, but also track x, y, z.  And maybe most importantly, secondary vertices.

It must be necessary to include similar variables at the generator level.  How to extract them properly need to be explored searching the code is always the best route, but one can also check [this workbook](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookGenParticleCandidate) and links therein (if available).

It could of help to check [these matching snippets](https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/blob/master/src/AOD2NanoAOD.cc#L666) from Stefan's code.

**Comment by JonaJJSJ-crypto** [comment]
After finishing #7  the geometry seems to not obey a displaced vertex as expected. I bealive for the same reasons we discussed. Since Lhe files already containing the decayed process don't consider the particle as a long living one. The tool that i found for this analysis is this (https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCandidateModules#ParticleDecayDrawer_Utility) and the results are these.
![DecayTree](https://user-images.githubusercontent.com/78813250/123343806-1e58ce80-d518-11eb-8e4e-abb235a3a0e2.png)

**Comment by caredg** [comment]
From @JonaJJSJ-crypto:

Acerca de los graficadores de partículas generadas el ejemplo que yo utilice para graficar partículas con pythia 6 es este [ParticleTreeDrawer](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCandidateModules#ParticleTreeDrawer_Utility). Es muy útil pues solo se necesita agregar esas líneas en el config file. Pero no he logrado que funcione con la simulación de pythia 8. Ahi mas abajo el ParticleListDrawer Utility funciona con pythia 8 pero no hay forma de filtrar en las particulas mas importantes para Pythia 8 por lo menos. Este formato es muy verbose por lo que no encontre una solucion sencilla trabajando con eso.
Estudiando un poco de la clase Gen particles, me refiero en el codigo de cmssw y la [twiki](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookGenParticleCandidate) entiendo que no se almacena realmente vertices secundarios. Al menos no con el detalle que se producen en la simulacion montecarlo.
Ahora hay formas de acceder a la Infromacion al nivel de montecarlo como en este [link](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookGeneration) en la seccion Accessing particle level MC data pero no funciona para pythia 8. Finalmente no recuerdo exactamente de que parte de latwiki saque esto pero Para Geant4 hay una parte en cmssw que almacena Infromacion directamente de HepMC(nivel de simulaicon) Pero no pude recuperar el articulo principal por el que termine llegando a esta parte de este [repositorio](https://github.com/cms-sw/cmssw/tree/CMSSW_5_3_X/SimG4Core).

**Comment by caredg** [comment]
from @JonaJJSJ-crypto 

Se que los vértices de nuestros eventos son desplazados. Porque corrí una simulación gemela en mi computador con la misma configuración que en cmssw, pero en mi caso teniendo acceso al archivo hep mc Verifique que esten desplazados los vértices. De hecho, esto lo comentamos alguna vez y el desplazamiento coincidía justamente con el predicho de unas cuantas decenas de micrómetros en unos casos o mas en otros

**Comment by caredg** [comment]
This should be contained by #35 (therefore closing)
