### ISSUE TITLE
No need to put root files in POET repository

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/Proyecto-de-Tesis#25]
There is no need to put so many root files in the [POET](https://github.com/JonaJJSJ-crypto/PhysObjectExtractorTool/tree/master/PhysObjectExtractor) fork.  If there is need, one example is more than enough, specially when there is no description of what the different ROOT files contain.  What is recoLW1, LW2, etc.?  As I said, no need for that.

Discipline also dictates to update the README file describing what general changes are included in this private fork of the POET framework.

**Comment by caredg** [comment]
ROOT files, and in general output files, should go into a cloud drive like onedrive or similar.  Github is no place for that (unless is a very light example)

**Comment by caredg** [comment]
Also, please fix these annoying warnings that appear at compilation:
```
>> Compiling edm plugin /afs/cern.ch/work/e/ecarrera/lw/simulations/CMSSW_5_3_32/src/PhysObjectExtractorTool/PhysObjectExtractor/src/ElectronAnalyzer.cc 
/afs/cern.ch/work/e/ecarrera/lw/simulations/CMSSW_5_3_32/src/PhysObjectExtractorTool/PhysObjectExtractor/src/ElectronAnalyzer.cc:344:11: warning: "/*" within comment [-Wcomment]
/afs/cern.ch/work/e/ecarrera/lw/simulations/CMSSW_5_3_32/src/PhysObjectExtractorTool/PhysObjectExtractor/src/ElectronAnalyzer.cc:347:11: warning: "/*" within comment [-Wcomment]
/afs/cern.ch/work/e/ecarrera/lw/simulations/CMSSW_5_3_32/src/PhysObjectExtractorTool/PhysObjectExtractor/src/ElectronAnalyzer.cc:492:1: warning: "/*" within comment [-Wcomment]
```

**Comment by JonaJJSJ-crypto** [comment]
Already removed .root files. And fixed the warnings during compilation
