### ISSUE TITLE
Get rid of printouts in the default version of POET

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/Proyecto-de-Tesis#26]
Please get rid of these printouts

```
PDG: -556 Status: 23 mother 1
pt: 218.877 eta: 2.93885 phi: 0.88742 mass: 200 vx: 0.243778 vy: 0.394885 vz: -2.59816 c: 0
  daugther: -556 Dpt: 249.214



PDG: 556 Status: 23 mother 1
pt: 218.877 eta: 1.27338 phi: -2.25417 mass: 200 vx: 0.243778 vy: 0.394885 vz: -2.59816 c: 0
  daugther: 556 Dpt: 192.86

......
```
 in the forked version of [POET](https://github.com/JonaJJSJ-crypto/PhysObjectExtractorTool).  This is good for testing, but should not be on in the repository

**Comment by JonaJJSJ-crypto** [comment]
Working on it Just one final check

**Comment by JonaJJSJ-crypto** [comment]
There are not any more printouts from cout<< lines, yet there are some prints from the reconstruction algorithm. This Problem should be corrected by not allowing the reconstruction using the same track two times
![PrintSecondaryvertex](https://user-images.githubusercontent.com/78813250/132937512-11cf4555-072c-44e3-9ddf-ede71bd669af.png)

**Comment by JonaJJSJ-crypto** [comment]
> There are not any more printouts from cout<< lines, yet there are some prints from the reconstruction algorithm. This Problem should be corrected by not allowing the reconstruction using the same track two times
> ![PrintSecondaryvertex](https://user-images.githubusercontent.com/78813250/132937512-11cf4555-072c-44e3-9ddf-ede71bd669af.png)

It seems to be an sporadic bug from the Reconstructing algorithm. I studied the problem by checking if there are some identical tracks in the reconstruction but that is not the issue. I also tried by clearing the vector responsible for the store, but that did not solve the problem neither. This issue will be now relocated in #28
