### ISSUE TITLE
Copy POET repository and detach from fork

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/Proyecto-de-Tesis#27]
Copy POET repository and detach from fork.  AFter working on #25 and #26 (please do it!, the stuff is still there), please detach the fork (it was good to preserve the structure) and make a copy of it to a new repository called `AcausalPoetAnalysis` instead of `PhysObjectExtractorTool`.  Please give @caredg and Santiago Paredes permissions to at least PR.   The [procedure](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/duplicating-a-repository#mirroring-a-repository) is pretty simple.

**Comment by JonaJJSJ-crypto** [comment]
Already done, you can finde the new [AcausalPOETAnalyzer](https://github.com/JonaJJSJ-crypto/AcausalPOETAnalyzer)

**Comment by JonaJJSJ-crypto** [comment]
Already done, you can find the new [AcausalPOETAnalyzer](https://github.com/JonaJJSJ-crypto/AcausalPOETAnalyzer), completely detach from POET repository. Also the previous forked repository was aliminated.
