### ISSUE TITLE
Select Simulated backgrounds based on the signal of the Acausal Process

### ISSUE THREAD

**Issue by JonaJJSJ-crypto** [JonaJJSJ-crypto/Proyecto-de-Tesis#34]

**Comment by JonaJJSJ-crypto** [comment]
Our signal was reconstructed considering one energetic Track (pt>20GeV) coming from the Lwe+/- decay and all the subsequent jets that are not required to be as energetic (pt>10GeV) but at least reliable tracks. Its also expected that the tracks that reconstruct our vertex not to be too spread (deltaR<3.5). Using this information I have choose 2 main candidates for Background. 
TTbarZ: this Background was choose since in this process There is the chance that an energetic Lepton share vertex with at least a jet. There is also a bunch of jets comming from this process that could perfectly be mistake as our signal. This set was also used as BackGround for Longlived Particles Analysis. This Information was extracted From this [article](https://inspirehep.net/files/69f00a88c677cd66002e31704feb315a), the main difference is taht we need our Z boson to decay Hadronically.
![ttbarZ](https://user-images.githubusercontent.com/78813250/134093605-4c2f7822-5a69-4910-9d8a-e96b81ac54e6.png)
WW and WZ: Both of this Events can produce that mix between jets coming from Z or W and an electron coming from W. The main source for this decay is from the previously presented paper and the chances for this event to happen. The Mc SImulations extracted from CernOpenData portal are [WZ](https://opendata.cern.ch/record/9977). In the case of WW there is no the exact process at least not in CernOpenData portal but one pretty similar is this set that includes a tau mediator [WWtoL+TaouToqq](https://opendata.cern.ch/record/9790)
![WW-WZ](https://user-images.githubusercontent.com/78813250/134095025-e18e21c3-6308-4e7f-9954-3260c8f3bf62.png)

**Comment by JonaJJSJ-crypto** [comment]
Here is the data set for simulated[ttbarZ](http://opendata.cern.ch/record/9519).

**Comment by caredg** [comment]
@JonaJJSJ-crypto Together with the previous question, we need to address the question of  QCD estimation.
