### ISSUE TITLE
Regenerate LHE files for LW simulation with 150,000 events

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/Proyecto-de-Tesis#40]
To improve statistics, let's simulate not 10,000 but 150,000 events for all 4 mass points.  I will re-run this simulation when this is ready.  The files in [this](https://github.com/JonaJJSJ-crypto/AcausalPOETAnalyzer/tree/main/AODgeneration/data) repository needs to be updated.

**Comment by JonaJJSJ-crypto** [comment]
Completed, due to the size of these new files they are uploaded as .gz files
