### ISSUE TITLE
Check the trigger in the real data

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/Proyecto-de-Tesis#45]
We need to check if there is fact triggers from our list (see #32) that are fully efficient.  If not, we have to take care of prescales.

**Comment by JonaJJSJ-crypto** [comment]
For Run C and B these triggers have no prescale "HLT_Photon36_CaloId10_Iso50_Photon22_CaloId10_Iso50_v*", "HLT_Photon36_CaloId10_Iso50_Photon22_R9Id85_v*",  "HLT_Photon36_R9Id85_Photon22_CaloId10_Iso50_v*", "HLT_Photon36_R9Id85_Photon22_R9Id85_v*"
And these are preescaled 
"HLT_Photon36_Photon22_v*", "HLT_Photon26_Photon18_v*"
Detailed info is pending to upload

**Comment by caredg** [comment]
We will try to keep these out of the pre-selection in order to keep the side-band for QCD background estimation
