### ISSUE TITLE
Check Z inv mass in electron channel

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/Proyecto-de-Tesis#51]
@JonaJJSJ-crypto as a sanity check, can you plot the reconstructed invariant mass of the Z decaying to electrons from the DY sample?  Let's see if the electrons are more or less correct.....

**Comment by JonaJJSJ-crypto** [comment]
In this Channel all seems to be allright
![imagen](https://user-images.githubusercontent.com/78813250/142701325-e0147910-620b-49b8-aa2e-d73cfefe78d2.png)

**Comment by caredg** [comment]
@JonaJJSJ-crypto, but this is at the generator level, how about reco?

**Comment by JonaJJSJ-crypto** [comment]
The Results are pretty similar
![imagen](https://user-images.githubusercontent.com/78813250/142705549-3d9bb400-5b5b-45ed-9d1c-e54e7d789d70.png)

**Comment by caredg** [comment]
@JonaJJSJ-crypto, esos histogramas son idénticos, algo no anda bien....

**Comment by caredg** [comment]
Ok, looks good.
